# Generated by Django 3.1.5 on 2021-01-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_answer_label_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='modified_at',
        ),
    ]
