# Generated by Django 3.1.5 on 2021-01-09 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210109_1938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
