# Generated by Django 3.1.5 on 2021-01-09 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_question_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='favorites',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
