# Generated by Django 3.1.5 on 2021-01-11 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_question_has_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='question_is_favorite',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_favorite',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core.question'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
